<a href="https://colab.research.google.com/github/PabloGP10/Extracci-n-de-Datos/blob/main/1_Extracci%C3%B3n_Datos1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [ ]:
#Convertir en dataframe
df= pd.read_csv("CountryTable.csv")
df

In [21]:
#Imprimimos las primeras filas o registros del Dataframe
df.head(5)

,code,name,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
continent,,,,,,,,,,,,,,
North America,ABW,Aruba,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
Asia,AFG,Afghanistan,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Africa,AGO,Angola,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
North America,AIA,Anguilla,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI
Europe,ALB,Albania,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS **

In [ ]:
#Filtro por objeto 
filtro1=df[df["continent"] == "Europe"]
filtro1

In [ ]:
#Convertir archivo filtrado a CSV
filtro1.to_csv("Entregable1.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro1.csv")

In [ ]:
#Filtro por objeto 
filtro12=df[df["name"] == "Aruba"]
filtro12

In [ ]:
#Convertir archivo filtrado a CSV
filtro12.to_csv("filtro12.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro12.csv")

In [ ]:
#Filtro por filas
#filtro2= df.iloc[300:302,: ]
filtro2=df.iloc[ [50, 100, 200] , : ]  #filas no consecutivas 
filtro2

In [ ]:
#Convertir archivo filtrado a CSV
filtro2.to_csv("filtro2.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro2.csv")

In [ ]:
#Filtro por filas
filtro21= df.iloc[0:20,: ]
#filtro2=df.iloc[ [50, 100, 200] , : ]  #filas no consecutivas 
filtro21

In [ ]:
#Convertir archivo filtrado a CSV
filtro21.to_csv("filtro21.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro21.csv")

In [16]:
#Filtro por columnas
filtro3=df.iloc[ : , 2:5]
#filtro3=df.iloc[ : , [1,4,6]]  #columnas no consecutivas 
filtro3

         continent                     region  surface_area
0    North America                  Caribbean         193.0
1             Asia  Southern and Central Asia      652090.0
2           Africa             Central Africa     1246700.0
3    North America                  Caribbean          96.0
4           Europe            Southern Europe       28748.0
..             ...                        ...           ...
234           Asia                Middle East      527968.0
235         Europe            Southern Europe      102173.0
236         Africa            Southern Africa     1221037.0
237         Africa             Eastern Africa      752618.0
238         Africa             Eastern Africa      390757.0

[239 rows x 3 columns]

In [ ]:
#Convertir archivo filtrado a CSV
filtro3.to_csv("filtro3.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro3.csv")

In [17]:
#Filtro por columnas
#filtro3=df.iloc[ : , 2:5]
filtro31=df.iloc[ : , [1,3,7]]  #columnas no consecutivas 
filtro31

             name                     region  life_expectancy
0           Aruba                  Caribbean             78.4
1     Afghanistan  Southern and Central Asia             45.9
2          Angola             Central Africa             38.3
3        Anguilla                  Caribbean             76.1
4         Albania            Southern Europe             71.6
..            ...                        ...              ...
234         Yemen                Middle East             59.8
235    Yugoslavia            Southern Europe             72.4
236  South Africa            Southern Africa             51.1
237        Zambia             Eastern Africa             37.2
238      Zimbabwe             Eastern Africa             37.8

[239 rows x 3 columns]

In [ ]:
#Convertir archivo filtrado a CSV
filtro31.to_csv("filtro31.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro31.csv")

In [23]:
#Filtro de filas vs columnas 
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()
df = pd.read_csv(io.BytesIO(uploaded['CountryTable.csv']), index_col=2)

Saving CountryTable.csv to CountryTable (3).csv

In [22]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
filtro4=df.loc[["Africa","North America"], ["head_of_state"]]
filtro4

                         head_of_state
continent
Africa         Jose Eduardo dos Santos
Africa                   Pierre Buyoya
Africa                 Mathieu Kerekou
Africa                 Blaise Compaore
Africa                 Festus G. Mogae
...                                ...
North America    Arthur N. R. Robinson
North America           George W. Bush
North America             Elisabeth II
North America             Elisabeth II
North America           George W. Bush

[95 rows x 1 columns]

In [ ]:
#Convertir archivo filtrado a CSV
filtro4.to_csv("filtro4.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro4.csv")

In [30]:
#Filtro de filas vs columnas 
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()
df = pd.read_csv(io.BytesIO(uploaded['CountryTable.csv']), index_col=3)

Saving CountryTable.csv to CountryTable (5).csv

In [32]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
filtro41=df.loc[["Caribbean","Antarctica"], ["government_form"]]
filtro41

                                         government_form
region
Caribbean   Nonmetropolitan Territory of The Netherlands
Caribbean                  Dependent Territory of the uK
Caribbean   Nonmetropolitan Territory of The Netherlands
Caribbean                        Constitutional Monarchy
Caribbean                        Constitutional Monarchy
Caribbean                        Constitutional Monarchy
Caribbean                           Socialistic Republic
Caribbean                  Dependent Territory of the uK
Caribbean                                       Republic
Caribbean                                       Republic
Caribbean                  Overseas Department of France
Caribbean                        Constitutional Monarchy
Caribbean                                       Republic
Caribbean                        Constitutional Monarchy
Caribbean                        Constitutional Monarchy
Caribbean                        Constitutional Monarchy
Caribbean                  Dependent Territory of the uK
Caribbean                  Overseas Department of France
Caribbean                         Commonwealth of the uS
Caribbean                  Dependent Territory of the uK
Caribbean                                       Republic
Caribbean                        Constitutional Monarchy
Caribbean                  Dependent Territory of the uK
Caribbean                                   uS Territory
Antarctica                              Co-administrated
Antarctica           Nonmetropolitan Territory of France
Antarctica                 Dependent Territory of Norway
Antarctica                        Territory of Australia
Antarctica                 Dependent Territory of the uK

In [ ]:
#Convertir archivo filtrado a CSV
filtro41.to_csv("filtro41.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro41.csv")

In [34]:
#Filtro por cabecera
filtro5=df.head(3)
filtro5

,code,name,continent,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
region,,,,,,,,,,,,,,
Caribbean,ABW,Aruba,North America,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
Southern and Central Asia,AFG,Afghanistan,Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Central Africa,AGO,Angola,Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO

In [ ]:
#Convertir archivo filtrado a CSV
filtro5.to_csv("filtro5.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro5.csv")

In [35]:
#Filtro por cabecera
filtro51=df.head(10)
filtro51

,code,name,continent,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
region,,,,,,,,,,,,,,
Caribbean,ABW,Aruba,North America,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
Southern and Central Asia,AFG,Afghanistan,Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Central Africa,AGO,Angola,Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
Caribbean,AIA,Anguilla,North America,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI
Southern Europe,ALB,Albania,Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL
Southern Europe,AND,Andorra,Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,NaN,55.0,AD
Caribbean,ANT,Netherlands Antilles,North America,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,33.0,AN
Middle East,ARE,united Arab Emirates,Asia,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al- Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65.0,AE
South America,ARG,Argentina,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rua,69.0,AR
Middle East,ARM,Armenia,Asia,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert KotSarjan,126.0,AM

In [ ]:
#Convertir archivo filtrado a CSV
filtro51.to_csv("filtro51.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro51.csv")

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [ ]:
#Filtro por comparacion
filtro6=df[df["independence_year"] > 1900]
filtro6

In [ ]:
#Convertir archivo filtrado a CSV
filtro6.to_csv("filtro6.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro6.csv")

In [41]:
#Filtro por comparacion
filtro61=df[df["population"] > 7000000]
filtro61

,code,name,continent,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
region,,,,,,,,,,,,,,
Southern and Central Asia,AFG,Afghanistan,Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Central Africa,AGO,Angola,Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
South America,ARG,Argentina,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rua,69.0,AR
Australia and New Zealand,AuS,Australia,Oceania,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135.0,Au
Western Europe,AuT,Austria,Europe,83859.0,1918.0,8091800,77.7,211860.0,206025.0,osterreich,Federal Republic,Thomas Klestil,1523.0,AT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Middle East,YEM,Yemen,Asia,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
Southern Europe,YuG,Yugoslavia,Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav KoStunica,1792.0,Yu
Southern Africa,ZAF,South Africa,Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
Eastern Africa,ZMB,Zambia,Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
Eastern Africa,ZWE,Zimbabwe,Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [ ]:
#Convertir archivo filtrado a CSV
filtro61.to_csv("filtro61.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro61.csv")

**FILTROS BASICOS CON CONETORES LOGICOS**

In [43]:
#Filtro Y
filtro7=df[(df["independence_year"] > 1900) & (df["population"] > 7000000)]
filtro7

,code,name,continent,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
region,,,,,,,,,,,,,,
Southern and Central Asia,AFG,Afghanistan,Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Central Africa,AGO,Angola,Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
Australia and New Zealand,AuS,Australia,Oceania,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135.0,Au
Western Europe,AuT,Austria,Europe,83859.0,1918.0,8091800,77.7,211860.0,206025.0,osterreich,Federal Republic,Thomas Klestil,1523.0,AT
Middle East,AZE,Azerbaijan,Asia,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azarbaycan,Federal Republic,Heydar aliyev,144.0,AZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Middle East,YEM,Yemen,Asia,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
Southern Europe,YuG,Yugoslavia,Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav KoStunica,1792.0,Yu
Southern Africa,ZAF,South Africa,Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
Eastern Africa,ZMB,Zambia,Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
Eastern Africa,ZWE,Zimbabwe,Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [ ]:
#Filtro o
filtro8=df[(df["Periodo"] > 2006) | (df["Sexo"] == "Mujeres")]
filtro8

,Periodo,Trimestre,Sexo,Poblacion_ocupada_en_la_industria_manufacturera,Poblaci n_ocupada,Tasa_de_ocupaci n_en_la_industria_manufacturera
Entidad_Federativa,,,,,,
Nacional,2005,1,Mujeres,2690296,14843275,18.124679360000000000000
Aguascalientes,2005,1,Mujeres,28430,145656,19.518591750000000000000
Baja California,2005,1,Mujeres,103697,398911,25.995021450000000000000
Baja California Sur,2005,1,Mujeres,4103,75648,5.4238049920000000000000
Campeche,2005,1,Mujeres,17935,110090,16.291216280000000000000
...,...,...,...,...,...,...
Veracruz,2022,1,Mujeres,107640,1190733,9.0398099320000000000000
Yucat n,2022,1,Hombres,101992,691397,14.751582670000000000000
Yucat n,2022,1,Mujeres,82759,478943,17.279509250000000000000
Zacatecas,2022,1,Hombres,44105,402326,10.962503040000000000000
Zacatecas,2022,1,Mujeres,39472,255761,15.43315830000000000000

In [ ]:
#Filtro not
filtro9=df[~(df["Periodo"] >= 2006) & ~(df["Sexo"] == "Mujeres")]
filtro9

,Periodo,Trimestre,Sexo,Poblacion_ocupada_en_la_industria_manufacturera,Poblaci n_ocupada,Tasa_de_ocupaci n_en_la_industria_manufacturera
Entidad_Federativa,,,,,,
Nacional,2005,1,Hombres,4384907,26597801,16.485975660000000000000
Aguascalientes,2005,1,Hombres,56407,246177,22.913188480000000000000
Baja California,2005,1,Hombres,167651,768989,21.801482210000000000000
Baja California Sur,2005,1,Hombres,9349,148814,6.2823390270000000000000
Campeche,2005,1,Hombres,17032,206708,8.2396423940000000000000
...,...,...,...,...,...,...
Tamaulipas,2005,4,Hombres,153867,814984,18.879757150000000000000
Tlaxcala,2005,4,Hombres,62629,274862,22.785616050000000000000
Veracruz,2005,4,Hombres,177063,1809574,9.7847891270000000000000
Yucat n,2005,4,Hombres,87066,488417,17.826160840000000000000
Zacatecas,2005,4,Hombres,26631,353848,7.5261129070000000000000

In [ ]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("Entregable1.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("Entregable1.csv")